import { Button } from 'antd'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { parseCookies } from 'nookies'

const Home: NextPage = () => {
  const jwt = parseCookies().jwt;

  return (
    <div className={styles.container}>
      <Head>
        <title>Authentication App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <Button href='/login' style={{ backgroundColor: "#fcba03", color: "#fff" }}>
          Sign In
        </Button>
        <Button href='/signup' style={{ backgroundColor: "#adfc03", color: "#fff" }}>
          Register
        </Button>
        <Button style={{ backgroundColor: "#0394fc", color: "#fff" }} {...jwt ? { href: "/restaraunts" } : { href: "/login" }}>
          Restaraunts
        </Button>

      </section>
      <footer className={styles.footer}>
        <a>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
